import io
import re
from datetime import datetime

from fastapi import APIRouter
from fastapi.responses import Response
from pydantic import BaseModel

router = APIRouter()

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor, black, white, Color
    from reportlab.lib.units import inch
    from reportlab.lib.enums import TA_LEFT, TA_CENTER
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.platypus.flowables import Flowable
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


class ExportRequest(BaseModel):
    content: str
    title: str = ""
    user_id: str = ""


# ─── PDF page callbacks (header + footer) ────────────────────────────────────

def _make_callbacks(doc_title: str):
    amber = HexColor("#f59e0b")
    gray = HexColor("#aaaaaa")
    dark = HexColor("#111111")
    date_str = datetime.now().strftime("%B %d, %Y")

    def _header_footer(canvas, doc):
        canvas.saveState()
        w, h = letter

        # Header — "JARVIS BY MG&CO" left, amber
        canvas.setFont("Helvetica-Bold", 8)
        canvas.setFillColor(amber)
        canvas.drawString(inch, h - 0.6 * inch, "JARVIS BY MG&CO")

        # Header — title right, gray
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(gray)
        canvas.drawRightString(w - inch, h - 0.6 * inch, doc_title[:80])

        # Header rule
        canvas.setStrokeColor(HexColor("#eeeeee"))
        canvas.setLineWidth(0.5)
        canvas.line(inch, h - 0.72 * inch, w - inch, h - 0.72 * inch)

        # Footer rule
        canvas.line(inch, 0.72 * inch, w - inch, 0.72 * inch)

        # Footer — left: branding, right: page number
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(gray)
        canvas.drawString(inch, 0.52 * inch, f"Generated by Jarvis by MG&CO · {date_str}")
        canvas.drawRightString(w - inch, 0.52 * inch, f"Page {doc.page}")

        canvas.restoreState()

    return _header_footer


# ─── Markdown line parser ─────────────────────────────────────────────────────

def _inline(text: str) -> str:
    """Convert **bold** and *italic* to reportlab XML tags."""
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # **bold**
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # *italic*
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    # `code`
    text = re.sub(r"`(.+?)`", r'<font name="Courier" size="9">\1</font>', text)
    return text


def _md_to_story(content: str, styles: dict) -> list:
    """Parse markdown text into a list of reportlab Flowables."""
    story = []
    lines = content.splitlines()
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Skip blank lines — add a small spacer
        if not stripped:
            story.append(Spacer(1, 4))
            i += 1
            continue

        # H2
        if stripped.startswith("## "):
            text = _inline(stripped[3:].strip())
            story.append(Spacer(1, 8))
            story.append(Paragraph(text, styles["h2"]))
            i += 1
            continue

        # H3
        if stripped.startswith("### "):
            text = _inline(stripped[4:].strip())
            story.append(Spacer(1, 4))
            story.append(Paragraph(text, styles["h3"]))
            i += 1
            continue

        # H1 (treat like H2)
        if stripped.startswith("# "):
            text = _inline(stripped[2:].strip())
            story.append(Spacer(1, 8))
            story.append(Paragraph(text, styles["h2"]))
            i += 1
            continue

        # Horizontal rule ---
        if re.match(r"^-{3,}$", stripped) or re.match(r"^_{3,}$", stripped):
            story.append(Spacer(1, 6))
            story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#cccccc")))
            story.append(Spacer(1, 6))
            i += 1
            continue

        # Bullet - item or * item
        if re.match(r"^[-*]\s+", stripped):
            text = _inline(re.sub(r"^[-*]\s+", "", stripped))
            story.append(Paragraph(f"• {text}", styles["bullet"]))
            i += 1
            continue

        # Numbered list  1. item
        if re.match(r"^\d+\.\s+", stripped):
            text = _inline(re.sub(r"^\d+\.\s+", "", stripped))
            num = re.match(r"^(\d+)\.", stripped).group(1)
            story.append(Paragraph(f"{num}. {text}", styles["bullet"]))
            i += 1
            continue

        # Skip markdown image/link syntax ![...](...) or metadata lines
        if stripped.startswith("![") or stripped.startswith("[!"):
            i += 1
            continue

        # Regular paragraph
        text = _inline(stripped)
        if text:
            story.append(Paragraph(text, styles["body"]))

        i += 1

    return story


# ─── Style factory ────────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()
    amber = HexColor("#f59e0b")
    dark = HexColor("#111111")

    return {
        "h2": ParagraphStyle(
            "H2",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=dark,
            spaceBefore=10,
            spaceAfter=4,
        ),
        "h3": ParagraphStyle(
            "H3",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=dark,
            spaceBefore=6,
            spaceAfter=3,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=11,
            leading=16,
            textColor=dark,
            spaceAfter=4,
        ),
        "bullet": ParagraphStyle(
            "Bullet",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=11,
            leading=15,
            textColor=dark,
            leftIndent=20,
            spaceAfter=3,
        ),
    }


# ─── Title extractor ─────────────────────────────────────────────────────────

def _extract_title(content: str, provided: str) -> str:
    if provided and provided.strip():
        return provided.strip()[:120]
    # First non-empty line, strip markdown
    for line in content.splitlines():
        line = line.strip()
        if line:
            title = re.sub(r"^#+\s*", "", line)
            title = re.sub(r"\*+", "", title)
            return title[:120]
    return "Jarvis Export"


# ─── Route ───────────────────────────────────────────────────────────────────

@router.post("/export/pdf")
async def export_pdf(request: ExportRequest):
    if not HAS_REPORTLAB:
        return Response(
            content=b"reportlab not installed",
            status_code=503,
            media_type="text/plain",
        )

    title = _extract_title(request.content, request.title)
    styles = _build_styles()
    callback = _make_callbacks(title)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
        title=title,
        author="Jarvis by MG&CO",
    )

    story = []

    # Document title block
    title_style = ParagraphStyle(
        "DocTitle",
        fontSize=20,
        fontName="Helvetica-Bold",
        textColor=HexColor("#111111"),
        spaceAfter=6,
        leading=24,
    )
    date_style = ParagraphStyle(
        "DocDate",
        fontSize=9,
        fontName="Helvetica",
        textColor=HexColor("#888888"),
        spaceAfter=16,
    )

    story.append(Paragraph(title, title_style))
    story.append(Paragraph(datetime.now().strftime("%B %d, %Y"), date_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#dddddd")))
    story.append(Spacer(1, 12))

    # Main content
    story.extend(_md_to_story(request.content, styles))

    doc.build(story, onFirstPage=callback, onLaterPages=callback)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    safe_title = re.sub(r"[^\w\s-]", "", title)[:40].strip().replace(" ", "-").lower()
    filename = f"jarvis-{safe_title or 'export'}-{timestamp}.pdf"

    return Response(
        content=buffer.getvalue(),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
