import io
from datetime import datetime

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.units import inch
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


def generate_pdf(walkthrough: dict) -> bytes:
    if not HAS_REPORTLAB:
        raise ImportError("reportlab not installed — add it to requirements.txt")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=72,
    )

    styles = getSampleStyleSheet()
    accent = HexColor("#c84b31")

    title_style = ParagraphStyle(
        "BizTitle", parent=styles["Title"],
        fontSize=22, textColor=accent, spaceAfter=10, fontName="Helvetica-Bold",
    )
    meta_style = ParagraphStyle(
        "BizMeta", parent=styles["Normal"],
        fontSize=9, textColor=HexColor("#888888"), spaceAfter=18,
    )
    intro_style = ParagraphStyle(
        "BizIntro", parent=styles["Normal"],
        fontSize=11, spaceAfter=16, leading=16,
    )
    step_num_style = ParagraphStyle(
        "BizStepNum", parent=styles["Normal"],
        fontSize=13, textColor=accent, spaceBefore=14, spaceAfter=5,
        fontName="Helvetica-Bold",
    )
    step_body_style = ParagraphStyle(
        "BizStepBody", parent=styles["Normal"],
        fontSize=11, spaceAfter=6, leading=15, leftIndent=16,
    )
    detail_style = ParagraphStyle(
        "BizDetail", parent=styles["Normal"],
        fontSize=10, spaceAfter=6, leading=14, leftIndent=16,
        textColor=HexColor("#666666"),
    )
    footer_style = ParagraphStyle(
        "BizFooter", parent=styles["Normal"],
        fontSize=8, textColor=HexColor("#aaaaaa"), alignment=1,
    )

    story = []

    story.append(Paragraph(walkthrough.get("title", "Walkthrough"), title_style))
    date_str = datetime.now().strftime("%B %d, %Y")
    story.append(Paragraph(f"Jarvis for Business · {date_str}", meta_style))

    intro = walkthrough.get("intro", "")
    if intro:
        story.append(Paragraph(intro, intro_style))

    for step in walkthrough.get("steps", []):
        num = step.get("step_number", "?")
        instruction = step.get("instruction", "").replace("<", "&lt;").replace(">", "&gt;")
        detail = step.get("detail", "")

        story.append(Paragraph(f"Step {num}", step_num_style))
        story.append(Paragraph(instruction, step_body_style))
        if detail:
            story.append(Paragraph(f"<i>{detail}</i>", detail_style))

    story.append(Spacer(1, 0.4 * inch))
    story.append(Paragraph("Generated by Jarvis for Business · MG&amp;CO Technologies", footer_style))

    doc.build(story)
    return buffer.getvalue()
