import io
import textwrap
from datetime import datetime

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    from reportlab.lib.units import inch
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


def generate_pdf(walkthrough: dict) -> bytes:
    if not HAS_REPORTLAB:
        raise ImportError("reportlab not installed — add it to requirements.txt")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=72,
    )

    styles = getSampleStyleSheet()
    accent = HexColor("#c84b31")

    title_style = ParagraphStyle(
        "BizTitle", parent=styles["Title"],
        fontSize=22, textColor=accent, spaceAfter=10, fontName="Helvetica-Bold",
    )
    meta_style = ParagraphStyle(
        "BizMeta", parent=styles["Normal"],
        fontSize=9, textColor=HexColor("#888888"), spaceAfter=18,
    )
    intro_style = ParagraphStyle(
        "BizIntro", parent=styles["Normal"],
        fontSize=11, spaceAfter=16, leading=16,
    )
    step_num_style = ParagraphStyle(
        "BizStepNum", parent=styles["Normal"],
        fontSize=13, textColor=accent, spaceBefore=14, spaceAfter=5,
        fontName="Helvetica-Bold",
    )
    step_body_style = ParagraphStyle(
        "BizStepBody", parent=styles["Normal"],
        fontSize=11, spaceAfter=6, leading=15, leftIndent=16,
    )
    detail_style = ParagraphStyle(
        "BizDetail", parent=styles["Normal"],
        fontSize=10, spaceAfter=6, leading=14, leftIndent=16,
        textColor=HexColor("#666666"),
    )
    footer_style = ParagraphStyle(
        "BizFooter", parent=styles["Normal"],
        fontSize=8, textColor=HexColor("#aaaaaa"), alignment=1,
    )

    story = []

    story.append(Paragraph(walkthrough.get("title", "Walkthrough"), title_style))
    date_str = datetime.now().strftime("%B %d, %Y")
    story.append(Paragraph(f"Jarvis for Business · {date_str}", meta_style))

    intro = walkthrough.get("intro", "")
    if intro:
        story.append(Paragraph(intro, intro_style))

    for step in walkthrough.get("steps", []):
        num = step.get("step_number", "?")
        instruction = step.get("instruction", "").replace("<", "&lt;").replace(">", "&gt;")
        detail = step.get("detail", "")

        story.append(Paragraph(f"Step {num}", step_num_style))
        story.append(Paragraph(instruction, step_body_style))
        if detail:
            story.append(Paragraph(f"<i>{detail}</i>", detail_style))

    story.append(Spacer(1, 0.4 * inch))
    story.append(Paragraph("Generated by Jarvis for Business · MG&amp;CO Technologies", footer_style))

    doc.build(story)
    return buffer.getvalue()


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _branded_cover(title: str, subtitle: str):
    """onFirstPage callback: dark MG&CO cover with title/subtitle."""

    def _draw(canvas, doc):
        canvas.saveState()
        width, height = letter
        canvas.setFillColor(HexColor("#131313"))
        canvas.rect(0, 0, width, height, fill=1, stroke=0)

        canvas.setFillColor(HexColor("#2d7ff9"))
        canvas.setFont("Helvetica-Bold", 10)
        canvas.drawString(0.9 * inch, height - 1.1 * inch, "JARVIS OS1 · MG&CO")

        canvas.setFillColor(HexColor("#ffffff"))
        canvas.setFont("Helvetica-Bold", 26)
        lines = textwrap.wrap(title, 36) or [title]
        y = height / 2 + 0.3 * inch + (0.45 * inch * (len(lines) - 1))
        for line in lines:
            canvas.drawString(0.9 * inch, y, line)
            y -= 0.45 * inch

        if subtitle:
            canvas.setFillColor(HexColor("#9aa0a6"))
            canvas.setFont("Helvetica", 12)
            canvas.drawString(0.9 * inch, y - 0.1 * inch, subtitle)

        canvas.setFillColor(HexColor("#666666"))
        canvas.setFont("Helvetica", 8)
        canvas.drawString(0.9 * inch, 0.7 * inch, datetime.now().strftime("%B %d, %Y"))
        canvas.restoreState()

    return _draw


def _branded_body(canvas, doc):
    """onLaterPages callback: clean white body pages with footer."""
    canvas.saveState()
    width, _ = letter
    canvas.setFillColor(HexColor("#aaaaaa"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(0.9 * inch, 0.5 * inch, "Generated by Jarvis OS1 · MG&CO Technologies")
    canvas.drawRightString(width - 0.9 * inch, 0.5 * inch, f"Page {doc.page}")
    canvas.restoreState()


def generate_branded_document_pdf(title: str, subtitle: str, sections: list[dict], footer_note: str = "") -> bytes:
    """
    Render a document with a dark MG&CO cover page (title + subtitle) followed by
    clean white body pages. `sections` is a list of {"heading": str, "body": str},
    where `body` lines starting with "- " render as bullets.
    """
    if not HAS_REPORTLAB:
        raise ImportError("reportlab not installed — add it to requirements.txt")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=72,
    )

    styles = getSampleStyleSheet()
    accent = HexColor("#2d7ff9")

    heading_style = ParagraphStyle(
        "DocHeading", parent=styles["Heading2"],
        fontSize=14, textColor=accent, spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "DocBody", parent=styles["Normal"],
        fontSize=10.5, leading=15, spaceAfter=4,
    )
    bullet_style = ParagraphStyle(
        "DocBullet", parent=body_style, leftIndent=16, bulletIndent=4,
    )
    note_style = ParagraphStyle(
        "DocNote", parent=styles["Normal"],
        fontSize=8.5, leading=12, textColor=HexColor("#888888"), spaceBefore=18,
    )

    story = [PageBreak()]
    for section in sections:
        heading = section.get("heading", "")
        body = section.get("body", "")
        if heading:
            story.append(Paragraph(_escape(heading), heading_style))
        for line in body.split("\n"):
            line = line.strip()
            if not line:
                continue
            escaped = _escape(line)
            if escaped.startswith("- "):
                story.append(Paragraph(escaped[2:], bullet_style, bulletText="•"))
            else:
                story.append(Paragraph(escaped, body_style))

    if footer_note:
        story.append(Spacer(1, 0.3 * inch))
        story.append(Paragraph(_escape(footer_note), note_style))

    doc.build(story, onFirstPage=_branded_cover(title, subtitle), onLaterPages=_branded_body)
    return buffer.getvalue()
